--path:"../src"
--cc:"clang"
--gc:"arc"
--panics:on
--threads:on
--define:"release"
--define:"useMalloc"
--forceBuild:on
when not defined(windows):
  --debugger:"native"
  --define:"noSignalHandler"
  --passc:"-fsanitize=thread -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
  --passl:"-fsanitize=thread -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
