name: Nim CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests with Thread Sanitizer
      run: nimble test
    - name: Run tests with Address Sanitizer
      run: nimble test -d:asan

  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests with Thread Sanitizer
      run: nimble test
    - name: Run tests with Address Sanitizer
      run: nimble test -d:asan

  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests with Thread Sanitizer
      run: nimble test
    - name: Run tests with Address Sanitizer
      run: nimble test -d:asan
